version: '2'
services:
  locator:
    image: apachegeode/geode
    expose:
     - "10334"
     - "1099"
     - "7575"
    #  - "1024"
    ports:
     - "1099:1099"
     - "10334:10334"
     - "7575:7575"
     - "7070:7070"
    volumes:
     - ${USER_DIR}/docker/scripts/:/scripts/
     - ${USER_DIR}/run/:/app/
     - ${USER_DIR}/target/:/applib/
    command: /scripts/startLocator.sh --mcast-port=0 --hostname-for-clients=${HOST_IP}

  server1:
    image: apachegeode/geode
    links:
     - locator:locator
    expose:
     - "8080"
     - "40404"
     - "1099"
    ports:
     - "40404:40404"
    volumes:
     - ${USER_DIR}/docker/scripts/:/scripts/
     - ${USER_DIR}/run/:/app/
     - ${USER_DIR}/target/:/applib/
    command: /scripts/startServer.sh --server-port=40404 --max-heap=1G --cache-xml-file=/scripts/cache.xml --hostname-for-clients=${HOST_IP} --classpath=/applib/vlingo-symbio-geode.jar

  server2:
    image: apachegeode/geode
    links:
      - locator:locator
    expose:
      - "8080"
      - "40405"
      - "1099"
    ports:
      - "40405:40405"
    volumes:
     - ${USER_DIR}/docker/scripts/:/scripts/
     - ${USER_DIR}/run/:/app/
     - ${USER_DIR}/target/:/applib/
    command: /scripts/startServer.sh --server-port=40405 --max-heap=1G --cache-xml-file=/scripts/cache.xml --hostname-for-clients=${HOST_IP} --classpath=/applib/vlingo-symbio-geode.jar
